/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendasRouteImport } from './routes/vendas'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PdvRouteImport } from './routes/pdv'
import { Route as MesasRouteImport } from './routes/mesas'
import { Route as MensagensRouteImport } from './routes/mensagens'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as EscolherRouteImport } from './routes/escolher'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ControleRouteImport } from './routes/controle'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicHooksNotifyAlertsRouteImport } from './routes/api/public/hooks/notify-alerts'

const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PdvRoute = PdvRouteImport.update({
  id: '/pdv',
  path: '/pdv',
  getParentRoute: () => rootRouteImport,
} as any)
const MesasRoute = MesasRouteImport.update({
  id: '/mesas',
  path: '/mesas',
  getParentRoute: () => rootRouteImport,
} as any)
const MensagensRoute = MensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const EscolherRoute = EscolherRouteImport.update({
  id: '/escolher',
  path: '/escolher',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ControleRoute = ControleRouteImport.update({
  id: '/controle',
  path: '/controle',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksNotifyAlertsRoute =
  ApiPublicHooksNotifyAlertsRouteImport.update({
    id: '/api/public/hooks/notify-alerts',
    path: '/api/public/hooks/notify-alerts',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/controle': typeof ControleRoute
  '/dashboard': typeof DashboardRoute
  '/escolher': typeof EscolherRoute
  '/financeiro': typeof FinanceiroRoute
  '/login': typeof LoginRoute
  '/mensagens': typeof MensagensRoute
  '/mesas': typeof MesasRoute
  '/pdv': typeof PdvRoute
  '/privacidade': typeof PrivacidadeRoute
  '/produtos': typeof ProdutosRoute
  '/termos': typeof TermosRoute
  '/usuarios': typeof UsuariosRoute
  '/vendas': typeof VendasRoute
  '/api/public/hooks/notify-alerts': typeof ApiPublicHooksNotifyAlertsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/controle': typeof ControleRoute
  '/dashboard': typeof DashboardRoute
  '/escolher': typeof EscolherRoute
  '/financeiro': typeof FinanceiroRoute
  '/login': typeof LoginRoute
  '/mensagens': typeof MensagensRoute
  '/mesas': typeof MesasRoute
  '/pdv': typeof PdvRoute
  '/privacidade': typeof PrivacidadeRoute
  '/produtos': typeof ProdutosRoute
  '/termos': typeof TermosRoute
  '/usuarios': typeof UsuariosRoute
  '/vendas': typeof VendasRoute
  '/api/public/hooks/notify-alerts': typeof ApiPublicHooksNotifyAlertsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/controle': typeof ControleRoute
  '/dashboard': typeof DashboardRoute
  '/escolher': typeof EscolherRoute
  '/financeiro': typeof FinanceiroRoute
  '/login': typeof LoginRoute
  '/mensagens': typeof MensagensRoute
  '/mesas': typeof MesasRoute
  '/pdv': typeof PdvRoute
  '/privacidade': typeof PrivacidadeRoute
  '/produtos': typeof ProdutosRoute
  '/termos': typeof TermosRoute
  '/usuarios': typeof UsuariosRoute
  '/vendas': typeof VendasRoute
  '/api/public/hooks/notify-alerts': typeof ApiPublicHooksNotifyAlertsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clientes'
    | '/configuracoes'
    | '/controle'
    | '/dashboard'
    | '/escolher'
    | '/financeiro'
    | '/login'
    | '/mensagens'
    | '/mesas'
    | '/pdv'
    | '/privacidade'
    | '/produtos'
    | '/termos'
    | '/usuarios'
    | '/vendas'
    | '/api/public/hooks/notify-alerts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clientes'
    | '/configuracoes'
    | '/controle'
    | '/dashboard'
    | '/escolher'
    | '/financeiro'
    | '/login'
    | '/mensagens'
    | '/mesas'
    | '/pdv'
    | '/privacidade'
    | '/produtos'
    | '/termos'
    | '/usuarios'
    | '/vendas'
    | '/api/public/hooks/notify-alerts'
  id:
    | '__root__'
    | '/'
    | '/clientes'
    | '/configuracoes'
    | '/controle'
    | '/dashboard'
    | '/escolher'
    | '/financeiro'
    | '/login'
    | '/mensagens'
    | '/mesas'
    | '/pdv'
    | '/privacidade'
    | '/produtos'
    | '/termos'
    | '/usuarios'
    | '/vendas'
    | '/api/public/hooks/notify-alerts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientesRoute: typeof ClientesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ControleRoute: typeof ControleRoute
  DashboardRoute: typeof DashboardRoute
  EscolherRoute: typeof EscolherRoute
  FinanceiroRoute: typeof FinanceiroRoute
  LoginRoute: typeof LoginRoute
  MensagensRoute: typeof MensagensRoute
  MesasRoute: typeof MesasRoute
  PdvRoute: typeof PdvRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ProdutosRoute: typeof ProdutosRoute
  TermosRoute: typeof TermosRoute
  UsuariosRoute: typeof UsuariosRoute
  VendasRoute: typeof VendasRoute
  ApiPublicHooksNotifyAlertsRoute: typeof ApiPublicHooksNotifyAlertsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdv': {
      id: '/pdv'
      path: '/pdv'
      fullPath: '/pdv'
      preLoaderRoute: typeof PdvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mesas': {
      id: '/mesas'
      path: '/mesas'
      fullPath: '/mesas'
      preLoaderRoute: typeof MesasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensagens': {
      id: '/mensagens'
      path: '/mensagens'
      fullPath: '/mensagens'
      preLoaderRoute: typeof MensagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escolher': {
      id: '/escolher'
      path: '/escolher'
      fullPath: '/escolher'
      preLoaderRoute: typeof EscolherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controle': {
      id: '/controle'
      path: '/controle'
      fullPath: '/controle'
      preLoaderRoute: typeof ControleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/notify-alerts': {
      id: '/api/public/hooks/notify-alerts'
      path: '/api/public/hooks/notify-alerts'
      fullPath: '/api/public/hooks/notify-alerts'
      preLoaderRoute: typeof ApiPublicHooksNotifyAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientesRoute: ClientesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ControleRoute: ControleRoute,
  DashboardRoute: DashboardRoute,
  EscolherRoute: EscolherRoute,
  FinanceiroRoute: FinanceiroRoute,
  LoginRoute: LoginRoute,
  MensagensRoute: MensagensRoute,
  MesasRoute: MesasRoute,
  PdvRoute: PdvRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ProdutosRoute: ProdutosRoute,
  TermosRoute: TermosRoute,
  UsuariosRoute: UsuariosRoute,
  VendasRoute: VendasRoute,
  ApiPublicHooksNotifyAlertsRoute: ApiPublicHooksNotifyAlertsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
